Multiwoven/multiwoven-server

Gemfile, Gemfile.lock
[Fix] Facebook Custom Audience
[Fix] Change the Klaviyo icon
None
=> [Chore] Update the integration gem version to 0.1.17

app/serializers/sync_serializer.rb, spec/requests/api/v1/syncs_controller_spec.rb
[Fix] Add Model details in All Sync fetch API
None
Wrote unit test and tested it via postman
=> [Fix] Add Model details in All Sync fetch API

app/temporal/activities/schedule_sync_activity.rb, app/temporal/cli/setup.rb, app/temporal/cli/worker, app/temporal/middlewares/logging_middleware.rb, docker-compose.yml, spec/temporal/middlewares/logging_middleware_spec.rb
[Chore] Add logger middleware for temporal
None
Wrote unit test
=> [Chore] Add logger middleware for temporal

app/models/connector.rb, app/models/model.rb, app/models/sync.rb, spec/models/connector_spec.rb, spec/models/model_spec.rb, spec/models/sync_spec.rb
feat: Add default scope for Connector, Model and Sync
None
Wrote unit test and tested the API locally
=> feat: Add default scope for Connector, Model and Sync

README.md
- Updated README as per the main repo.
- Minor corrections.
=> Updated README as per the main repo

config/initializers/active_model_serializers.rb
fix: Change key transform from underscore to unaltered
None
Tested it via postman
=> fix: Change key_transform from underscore to unaltered

.github/ISSUE_TEMPLATE/bug_report_template.md, .github/ISSUE_TEMPLATE/documentation_update_template.md, .github/ISSUE_TEMPLATE/feature_request_template.md, .github/pull_request_template.md
Add GitHub Template for issues and PR
None
Viewed MD preview
=> docs: Add github template for multiwoven server

app/models/connector.rb, spec/models/connector_spec.rb
=> fix: prevent orphan sync without connector

Gemfile, Gemfile.lock
=> chore: Update integration gem to 0.1.30

.github/workflows/ci.yml
=> Update ci.yml to bypass cc-test-reporter steps

app/contracts/sync_record_contracts.rb, app/contracts/sync_run_contracts.rb, app/controllers/api/v1/sync_records_controller.rb, app/controllers/api/v1/sync_runs_controller.rb, app/serializers/sync_record_serializer.rb, app/serializers/sync_run_serializer.rb, config/routes.rb, lib/reverse_etl/extractors/incremental_delta.rb, spec/contracts/sync_record_contracts_spec.rb, spec/contracts/sync_run_contracts_spec.rb, spec/requests/api/v1/sync_records_controller_spec.rb, spec/requests/api/v1/sync_runs_controller_spec.rb
=> feat: sync run and sync record controller

.gitignore, app/interactors/reports/activity_report.rb, spec/interactors/reports/activity_report_spec.rb, spec/requests/api/v1/reports_controller_spec.rb
=> fix: time slice count issue in report api

.gitignore, db/migrate/20240305070953_add_primary_key_sync_id_unique_index_to_sync_records.rb, db/schema.rb, lib/reverse_etl/extractors/incremental_delta.rb, spec/lib/reverse_etl/loaders/standard_spec.rb, spec/models/sync_record_spec.rb, spec/requests/api/v1/sync_records_controller_spec.rb
=> bug: fix the duplicate primary key in sync records

Gemfile, Gemfile.lock, app/controllers/api/v1/syncs_controller.rb, app/models/sync.rb, app/temporal/activities/terminate_workflow_activity.rb, app/temporal/cli/worker, app/temporal/workflows/terminate_workflow.rb, db/migrate/20240305120454_add_discarded_at_to_syncs.rb, db/schema.rb
=> feat: terminate workflows for a delete sync

app/models/sync.rb, app/models/sync_run.rb, db/migrate/20240306045911_add_discarded_at_to_sync_runs.rb, db/schema.rb, spec/models/sync_run_spec.rb, spec/models/sync_spec.rb
=> fix: soft delete for sync run

app/models/sync.rb, app/temporal/activities/terminate_workflow_activity.rb, spec/models/sync_spec.rb
=> fix: sync soft delete temporal retry fix

Gemfile, Gemfile.lock
=> chore: update integration gem to 0.1.33

.env.example, Dockerfile, Dockerfile.dev
=> feat: add databricks odbc driver

app/interactors/workspace_users/create.rb, app/models/user.rb, config/initializers/devise.rb, db/migrate/20240314102143_add_lockable_to_users.rb, db/schema.rb, spec/controllers/api/v1/auth_controller_spec.rb, spec/factories/users.rb, spec/interactors/authentication/login_spec.rb, spec/interactors/authentication/signup_spec.rb, spec/interactors/workspace_users/create_spec.rb, spec/models/user_spec.rb
=> fix: password policy

config/initializers/custom_pagination_links.rb, config/initializers/kaminari_config.rb, spec/requests/api/v1/connectors_controller_spec.rb, spec/requests/api/v1/models_controller_spec.rb, spec/requests/api/v1/sync_records_controller_spec.rb, spec/requests/api/v1/sync_runs_controller_spec.rb, spec/requests/api/v1/syncs_controller_spec.rb
=> fix: pagination link invalid

app/contracts/sync_run_contracts.rb, app/controllers/api/v1/sync_runs_controller.rb, config/routes.rb, spec/contracts/sync_run_contracts_spec.rb, spec/requests/api/v1/sync_runs_controller_spec.rb
=> feat: sync run api by sync id

Gemfile, Gemfile.lock, app/models/sync.rb, app/temporal/activities/extractor_activity.rb, app/temporal/activities/loader_activity.rb, lib/reverse_etl/extractors/base.rb, lib/reverse_etl/extractors/full_refresh.rb, lib/reverse_etl/extractors/incremental_delta.rb, lib/reverse_etl/loaders/standard.rb, spec/factories/syncs.rb, spec/lib/reverse_etl/extractors/full_refresh_spec.rb, spec/lib/reverse_etl/loaders/standard_spec.rb, spec/temporal/activities/extractor_activity_spec.rb
=> feat: support sync mode full refresh

Gemfile, Gemfile.lock
chore: Update gem multiwoven integrations gem version
None
None
=> chore: Update gem multiwoven integrations gem version

Gemfile, Gemfile.lock
chore: Update gem version to 0.1.40
None
None
=> chore: Update gem version to 0.1.40

Gemfile, Gemfile.lock
chore: Update integration gem to 0.1.41
None
None
=> chore: Update integration gem to 0.1.41

Gemfile, Gemfile.lock, app/models/catalog.rb, config/initializers/devise.rb
=> chore: update gem 0.1.43

Gemfile, Gemfile.lock
=> chore: update gem version 0.1.45

Gemfile, Gemfile.lock
=> Bump integration gem to 1.47

app/temporal/activities/extractor_activity.rb, lib/reverse_etl/extractors/full_refresh.rb, spec/lib/reverse_etl/extractors/full_refresh_spec.rb
=> feat: disable records cleanup in full refresh.

Gemfile, Gemfile.lock
feat: Update gem version  0.1.48
None
Not tested
=> feat: Update gem version  0.1.48

lib/liquid/custom_filters.rb, spec/lib/liquid/custom_filters_spec.rb
feat: Add custom filter to_datetime
None
Wrote rspec
=> feat: Add custom filter to_datetime

Gemfile, Gemfile.lock
Update gem to 0.1.50
None
None
=> Update gem to 0.1.50

Gemfile, Gemfile.lock
Update integration gem to 0.1.51
None
None
=> Update integration gem to 0.1.51

Gemfile, Gemfile.lock
=> chore: upgrade gem 0.1.52
